In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('spam.csv')

## DATA CLEANING

In [ ]:
df.sample(4)

       v1                                                 v2 col1 col2 col3
4517  ham  That sucks. So what do you got planned for you...  NaN  NaN  NaN
205   ham  �� say until like dat i dun buy ericsson oso c...  NaN  NaN  NaN
2856  ham  Today i'm not workin but not free oso... Gee.....  NaN  NaN  NaN
3432  ham  Christmas is An occasion that is Celebrated as...  NaN  NaN  NaN

In [ ]:
df.isnull().sum()

v1         0
v2         0
col1    5522
col2    5560
col3    5566
dtype: int64

In [ ]:
df.shape

(5572, 5)

In [ ]:
df.drop(columns=['col1','col2','col3'],inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(403)

In [ ]:
df.drop_duplicates(keep='first',inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.sample(5)

        v1                                                 v2
437    ham               How long does applebees fucking take
2427   ham      Do you think i can move  &lt;#&gt;  in a week
93    spam  Please call our customer service representativ...
3263   ham  I will send them to your email. Do you mind  &...
4869   ham  Dip's cell dead. So i m coming with him. U bet...

In [ ]:
df.rename(columns = {'v1': 'output','v2': 'message'}, inplace=True)

     output                                            message
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham              Will �_ b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5169 rows x 2 columns]